/**
 * TypeScript types mirroring the database schema exactly.
 * Column names use camelCase matching Prisma's generated client.
 *
 * These types describe what comes out of the DB.
 * For API input/output shapes use the domain types in alert.ts / offer.ts.
 */

// =============================================================================
// Enums
// =============================================================================

export type AlertStatus      = 'active' | 'paused' | 'archived'
export type TripType         = 'one_way' | 'round_trip'
export type NotifFrequency   = 'instant' | 'daily_digest'
export type NotifChannel     = 'telegram' | 'email'
export type NotifReason      = 'below_threshold' | 'price_drop'
export type NotifStatus      = 'pending' | 'sent' | 'failed'
export type SearchRunStatus  = 'ok' | 'empty' | 'error'

// =============================================================================
// TABLE: users
// =============================================================================

export interface DbUser {
  id:                    string       // UUID — same as auth.users.id
  email:                 string
  telegramChatId:        bigint | null
  telegramUsername:      string | null
  telegramLinkToken:     string | null
  telegramLinkExpiresAt: Date | null
  telegramConnectedAt:   Date | null
  createdAt:             Date
  updatedAt:             Date
}

// =============================================================================
// TABLE: alerts
// =============================================================================

export interface DbAlert {
  id:                 string
  userId:             string
  status:             AlertStatus
  origin:             string
  destination:        string
  tripType:           TripType
  departDateFrom:     Date
  departDateTo:       Date | null
  returnDateFrom:     Date | null
  returnDateTo:       Date | null
  cabinClass:         string       // always 'business' in MVP
  maxPrice:           number       // Prisma returns Decimal; code converts to number
  currency:           string       // 'EUR' | 'USD'
  maxStops:           number       // 0 | 1 | 2
  maxDurationMinutes: number | null
  nearbyAirports:     boolean
  notifFrequency:     NotifFrequency
  lastCheckedAt:      Date | null
  bestPriceSeen:      number | null
  createdAt:          Date
  updatedAt:          Date
}

// =============================================================================
// TABLE: search_runs
// One row per cron execution per alert.
// =============================================================================

export interface DbSearchRun {
  id:               string
  alertId:          string
  provider:         string           // 'mock' | 'amadeus' | 'duffel'
  runAt:            Date
  durationMs:       number | null    // wall-clock ms for the provider call
  rawResultsCount:  number           // total offers returned by provider
  filteredCount:    number           // after applying alert constraints
  worthyCount:      number           // passed worthyToNotify()
  status:           SearchRunStatus
  errorMessage:     string | null
}

// Insert shape — id and runAt are generated by DB
export type DbSearchRunInsert = Omit<DbSearchRun, 'id' | 'runAt'>

// =============================================================================
// TABLE: flight_offers
// =============================================================================

export interface DbFlightOffer {
  id:              string
  alertId:         string
  searchRunId:     string | null
  provider:        string
  origin:          string
  destination:     string
  departAt:        Date
  arriveAt:        Date
  returnDepartAt:  Date | null
  returnArriveAt:  Date | null
  price:           number
  currency:        string
  stops:           number
  durationMinutes: number
  isFullBusiness:  boolean
  airlineCodes:    string[]
  deepLink:        string
  rawData:         Record<string, unknown>
  hashForDedup:    string   // SHA-256, 64 hex chars
  foundAt:         Date
}

// Insert shape — id and foundAt are generated by DB
export type DbFlightOfferInsert = Omit<DbFlightOffer, 'id' | 'foundAt'>

// =============================================================================
// TABLE: notifications
// =============================================================================

export interface DbNotification {
  id:           string
  alertId:      string
  offerId:      string
  userId:       string
  channel:      NotifChannel
  reason:       NotifReason
  aiInsight:    string | null
  status:       NotifStatus
  errorMessage: string | null
  sentAt:       Date | null
  createdAt:    Date
}

// Insert shape
export type DbNotificationInsert = Omit<DbNotification, 'id' | 'createdAt'>

// =============================================================================
// VIEW: alert_summary (read-only, includes aggregates)
// =============================================================================

export interface DbAlertSummary extends DbAlert {
  totalOffersFound: number
  lastRunAt:        Date | null
  lastRunStatus:    SearchRunStatus | null
}

// =============================================================================
// Utility: Prisma Decimal → number
// Prisma returns Decimal objects for NUMERIC columns.
// Use this when you need a plain number from a Prisma row.
// =============================================================================

export function decimalToNumber(value: { toNumber(): number } | number | null): number | null {
  if (value === null || value === undefined) return null
  if (typeof value === 'number') return value
  return value.toNumber()
}
